logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    pl.b4jd1k.airbnb_clone_back: INFO

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/airbnb_clone
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: airbnb_clone
  liquibase:
    contexts: prod
    default-schema: airbnb_clone
